(()=>{
const app=document.querySelector("#app"),KEY="discovery-up-profile-v1",DAY="discovery-up-day-",levels=[
 ["Déclic",0],["Mise en mouvement",70],["Élan",160],["Rythme",270],["Régularité",390],["Engagement",520],["Progression",660],["Endurance",810],["Équilibre",970],["Autonomie",1130],["Vitalité",1280],["Terrain solide",1420]
],weekNames=["Lun","Mar","Mer","Jeu","Ven","Sam","Dim"],habits=[
 ["🌬️","Respirer","2 à 3 minutes de respiration consciente"],["🏃","Bouger","Marche, course ou micro-séance"],["🥗","Manger","Au moins un repas brut et sain"],["🌙","Récupérer","Une action favorable à la récupération"],["🎯","Objectif personnel",""]
],missions={walk:[
 ["Marche consciente","Marche 8 minutes en observant ta respiration."],["Posture active","Marche 10 minutes, épaules relâchées et regard loin devant."],["Mobilité express","Mobilise doucement chevilles, hanches et épaules pendant 4 minutes."],["Variation d’allure","Alterne 1 minute vive et 1 minute facile pendant 10 minutes."],["Escaliers faciles","Ajoute une volée d’escaliers ou une légère montée à ton trajet."],["Récupération active","Marche 12 minutes à une allure qui te permet de parler."],["Pas du week-end","Profite de ta journée pour ajouter 15 minutes de marche plaisir."],["Équilibre","Tiens 30 secondes sur chaque pied près d’un appui."],["Bras actifs","Pendant 8 minutes de marche, accompagne le mouvement avec les bras."],["Sortie progressive","Ajoute 5 minutes à ta durée habituelle, sans forcer."],["Respiration rythmée","Pendant 5 minutes, trouve un rythme respiratoire confortable."],["Terrain varié","Marche sur un parcours légèrement différent et reste attentif à tes appuis."]
],run:[
 ["Départ facile","Cours ou alterne marche et course pendant 8 minutes à allure confortable."],["Cadence souple","Réalise 6 fois 30 secondes dynamiques, avec 60 secondes faciles."],["Mobilité du coureur","Mobilise chevilles, hanches et épaules pendant 4 minutes."],["Endurance douce","Réalise 12 minutes en pouvant encore parler."],["Relances","Ajoute 4 accélérations progressives de 15 secondes."],["Récupération","Marche 15 minutes ou réalise une mobilité douce."],["Sortie plaisir","Choisis un parcours agréable sans objectif de vitesse."],["Technique","Pendant 6 minutes, garde une foulée légère et le haut du corps relâché."],["Alternance","Répète 5 fois 1 minute de course et 1 minute de marche."],["Progression","Ajoute 3 minutes à ta durée habituelle si les sensations sont bonnes."],["Respiration","Trouve une allure où ta respiration reste maîtrisée pendant 10 minutes."],["Retour au calme","Termine ta séance par 5 minutes de marche et une respiration lente."]
]};
let profile=load(KEY,{ready:false,program:"walk",custom:"Hydratation",created:new Date().toISOString()});
function load(key,fallback){try{return JSON.parse(localStorage.getItem(key))||fallback}catch{return fallback}}
function save(){localStorage.setItem(KEY,JSON.stringify(profile))}
function dateKey(date=new Date()){const y=date.getFullYear(),m=String(date.getMonth()+1).padStart(2,"0"),d=String(date.getDate()).padStart(2,"0");return `${y}-${m}-${d}`}
function data(date=new Date()){return load(DAY+dateKey(date),{checks:[false,false,false,false,false],source:"",finished:false})}
function write(day,value){localStorage.setItem(DAY+dateKey(day),JSON.stringify(value))}
function points(d=data()){return d.checks.filter(Boolean).length}
function allDays(){const out=[];for(let i=0;i<localStorage.length;i++){const k=localStorage.key(i);if(k?.startsWith(DAY)){const d=load(k,null);if(d)out.push({key:k.slice(DAY.length),...d})}}return out.sort((a,b)=>a.key.localeCompare(b.key))}
function total(){return allDays().reduce((n,d)=>n+points(d),0)}
function levelInfo(){const t=total();let i=0;levels.forEach((l,n)=>{if(t>=l[1])i=n});return {index:i,number:i+1,name:levels[i][0],next:levels[i+1]||null,total:t}}
function streak(){const set=new Set(allDays().filter(d=>points(d)>=3).map(d=>d.key));let cursor=new Date();cursor.setHours(0,0,0,0);if(!set.has(dateKey(cursor)))cursor.setDate(cursor.getDate()-1);let n=0;while(set.has(dateKey(cursor))){n++;cursor.setDate(cursor.getDate()-1)}return n}
function monday(date=new Date()){const d=new Date(date);d.setHours(0,0,0,0);d.setDate(d.getDate()-((d.getDay()+6)%7));return d}
function weekDates(){const m=monday();return Array.from({length:7},(_,i)=>{const d=new Date(m);d.setDate(m.getDate()+i);return d})}
function weeklyHabit(i){return weekDates().reduce((n,d)=>n+(data(d).checks[i]?1:0),0)}
function weeklyPoints(){return weekDates().reduce((n,d)=>n+points(data(d)),0)}
function challenge(){const start=new Date(2026,0,1),now=new Date();start.setHours(0,0,0,0);now.setHours(0,0,0,0);const days=Math.floor((now-start)/86400000),list=missions[profile.program];return list[((days%list.length)+list.length)%list.length]}
function difficulty(text,level){if(level<4)return text;if(level<8)return text+" Ajoute quelques minutes seulement si tu te sens bien.";return text+" Choisis une variante légèrement plus exigeante si elle reste confortable."}
function pulse(level){return `./assets/pulse/level-${String(level).padStart(2,"0")}.webp`}
function toast(msg){document.body.insertAdjacentHTML("beforeend",`<div class="toast">${msg}</div>`);setTimeout(()=>document.querySelector(".toast")?.remove(),1800)}
function render(){if(!profile.ready)return onboarding();const today=new Date(),d=data(today),lv=levelInfo(),next=lv.next?lv.next[1]:lv.total,prev=levels[lv.index][1],pct=lv.next?Math.round((lv.total-prev)/(next-prev)*100):100,mission=challenge(),week=weekDates();
 const rows=habits.map((h,i)=>`<div class="habit"><span class="habit-icon">${h[0]}</span><span class="habit-name">${i===4?profile.custom:h[2]}</span><button class="check ${d.checks[i]?"on":""}" data-check="${i}" aria-pressed="${d.checks[i]}">${d.checks[i]?"✓":""}</button></div>`).join("");
 const days=week.map((date,i)=>{const p=points(data(date));return `<div class="day ${p>=3?"done":""} ${dateKey(date)===dateKey(today)?"today":""}">${weekNames[i]}<b>${p>=3?"✓":p}</b></div>`}).join("");
 const chart=habits.map((h,i)=>{const n=weeklyHabit(i);return `<div class="chart-row"><span>${h[0]} ${i===4?profile.custom:h[1]}</span><div class="bar"><i style="width:${n/7*100}%"></i></div><b>${n}/7</b></div>`}).join("");
 app.innerHTML=`<div class="shell"><header class="topbar"><img class="brand" src="./logo-discovery-up.svg" alt="Discovery UP"><button class="icon-button settings" aria-label="Réglages">⚙</button></header><div class="season">PROGRAMME 10 MOIS · ${profile.program==="walk"?"MARCHE ACTIVE":"DISCOVERY RUN"}</div><section class="dashboard"><div class="stat"><span>NIVEAU</span><strong>${lv.number}</strong><small>${lv.name}</small></div><div class="stat"><span>SÉRIE</span><strong>${streak()}</strong><small>JOURS À 3 / 5</small></div></section><section class="hero"><img class="pulse" src="${pulse(lv.number)}" alt="Pulse au niveau ${lv.number}"><div class="hero-copy"><h1>${points(d)>=3?"Belle régularité !":"Ton terrain se construit"}</h1><p>${lv.next?`${lv.next[1]-lv.total} points avant ${lv.next[0]}`:"Niveau maximal atteint"}</p><div class="meter"><span style="width:${Math.max(0,pct)}%"></span></div><div class="meter-label"><span>${lv.total} points</span><span>${pct}%</span></div></div></section><div class="week">${days}</div><section class="card"><div class="card-head"><h2>Aujourd’hui</h2><span class="date">${points(d)}/5</span></div>${rows}</section><section class="card mission"><span class="mission-tag">MISSION DU JOUR · NIVEAU ${lv.number}</span><h3>${mission[0]}</h3><p>${difficulty(mission[1],lv.number)}</p><div class="source-grid"><button class="source ${d.source==="mission"?"on":""}" data-source="mission">Mission réalisée</button><button class="source ${d.source==="coaching"?"on":""}" data-source="coaching">Séance de coaching</button><button class="source ${d.source==="personal"?"on":""}" data-source="personal">Activité personnelle</button><button class="source ${d.source==="recovery"?"on":""}" data-source="recovery">Récupération active</button></div></section><button class="finish" ${points(d)<3?"disabled":""}>${d.finished?"VOIR MON BILAN":"TERMINER MA JOURNÉE"}</button><section class="card"><div class="card-head"><h2>Mes habitudes cette semaine</h2><span class="date">${weeklyPoints()}/35</span></div>${chart}</section><div class="tools"><button class="tool export">Sauvegarder</button><label class="tool" for="restore">Restaurer</label><input id="restore" hidden type="file" accept="application/json"><button class="tool info">À propos</button></div><p class="privacy">🔒 Les données restent uniquement sur cet appareil.</p><div class="signature"><span>par</span><img src="./assets/discovery-sports.webp" alt="Discovery Sports"></div></div>`;bind()}
function onboarding(){app.innerHTML=`<div class="overlay"><section class="modal"><img class="brand" src="./logo-discovery-up.svg" alt="Discovery UP"><img class="pulse" src="./assets/pulse/level-01.webp" alt="Pulse"><h2>Bienvenue</h2><p>Choisis ton parcours. Tu pourras le modifier plus tard.</p><div class="choice"><button data-program="walk" class="${profile.program==="walk"?"on":""}">🚶<br>Marche Active</button><button data-program="run" class="${profile.program==="run"?"on":""}">🏃<br>Discovery Run</button></div><label for="custom">Ton objectif personnel</label><input id="custom" type="text" maxlength="32" value="${profile.custom}" placeholder="Ex. Hydratation"><button class="primary start">COMMENCER</button><div class="signature"><span>par</span><img src="./assets/discovery-sports.webp" alt="Discovery Sports"></div></section></div>`;app.querySelectorAll("[data-program]").forEach(b=>b.onclick=()=>{profile.program=b.dataset.program;onboarding()});app.querySelector(".start").onclick=()=>{profile.custom=app.querySelector("#custom").value.trim()||"Hydratation";profile.ready=true;save();render()}}
function settings(){app.insertAdjacentHTML("beforeend",`<div class="overlay"><section class="modal"><h2>Mes réglages</h2><label>Parcours</label><div class="choice"><button data-program="walk" class="${profile.program==="walk"?"on":""}">🚶<br>Marche Active</button><button data-program="run" class="${profile.program==="run"?"on":""}">🏃<br>Discovery Run</button></div><label for="custom">Objectif personnel</label><input id="custom" type="text" maxlength="32" value="${profile.custom}"><button class="primary save-settings">ENREGISTRER</button><button class="secondary close">ANNULER</button><button class="secondary reset">EFFACER MA PROGRESSION</button></section></div>`);const modal=app.querySelector(".overlay");modal.querySelectorAll("[data-program]").forEach(b=>b.onclick=()=>{profile.program=b.dataset.program;modal.querySelectorAll("[data-program]").forEach(x=>x.classList.toggle("on",x===b))});modal.querySelector(".save-settings").onclick=()=>{profile.custom=modal.querySelector("#custom").value.trim()||"Hydratation";save();render();toast("Réglages enregistrés")};modal.querySelector(".close").onclick=render;modal.querySelector(".reset").onclick=()=>{if(confirm("Effacer toute la progression Discovery UP sur cet appareil ?")){Object.keys(localStorage).filter(k=>k.startsWith("discovery-up-")).forEach(k=>localStorage.removeItem(k));location.reload()}}}
function summary(){const d=data(),lv=levelInfo(),score=points(d);d.finished=true;write(new Date(),d);app.insertAdjacentHTML("beforeend",`<div class="overlay"><section class="modal" style="text-align:center"><img class="pulse" src="${pulse(lv.number)}" alt="Pulse célèbre"><span class="mission-tag">+${score} POINT${score>1?"S":""}</span><h2>${score===5?"Journée complète !":score===4?"Très belle journée !":"Objectif atteint !"}</h2><p>🔥 Série actuelle : <b>${streak()} jour${streak()>1?"s":""}</b></p><p>${lv.next?`Encore ${lv.next[1]-lv.total} points avant le niveau ${lv.next[0]}.`:"Tu as atteint Terrain solide."}</p><p>Prochaine étape : reviens demain pour une nouvelle mission.</p><button class="primary close-summary">À DEMAIN</button><button class="secondary edit-summary">MODIFIER MES HABITUDES</button></section></div>`);app.querySelector(".close-summary").onclick=render;app.querySelector(".edit-summary").onclick=render}
function about(){app.insertAdjacentHTML("beforeend",`<div class="overlay"><section class="modal"><img class="brand" src="./logo-discovery-up.svg" alt="Discovery UP"><h2>À propos</h2><p>Discovery UP accompagne les membres de Marche Active et Discovery Run dans la construction d’habitudes santé régulières.</p><p>Les conseils restent généraux. En cas de problème de santé, de douleur persistante ou de doute, demande l’avis d’un professionnel de santé.</p><div class="signature"><span>une application de</span><img src="./assets/discovery-sports.webp" alt="Discovery Sports"></div><button class="primary close">FERMER</button></section></div>`);app.querySelector(".close").onclick=render}
function exportData(){const items={};Object.keys(localStorage).filter(k=>k.startsWith("discovery-up-")).forEach(k=>items[k]=localStorage.getItem(k));const a=document.createElement("a"),url=URL.createObjectURL(new Blob([JSON.stringify({format:"discovery-up",version:1,items},null,2)],{type:"application/json"}));a.href=url;a.download="progression-discovery-up.json";a.click();URL.revokeObjectURL(url)}
function restore(file){const r=new FileReader();r.onload=()=>{try{const x=JSON.parse(r.result);if(x.format!=="discovery-up"||!x.items)throw 0;Object.entries(x.items).forEach(([k,v])=>{if(k.startsWith("discovery-up-")&&typeof v==="string")localStorage.setItem(k,v)});location.reload()}catch{alert("Ce fichier de sauvegarde n’est pas valide.")}};r.readAsText(file)}
function bind(){app.querySelectorAll("[data-check]").forEach(b=>b.onclick=()=>{const d=data(),i=+b.dataset.check;d.checks[i]=!d.checks[i];d.finished=false;write(new Date(),d);render();toast(d.checks[i]?"Habitude validée +1":"Validation retirée")});app.querySelectorAll("[data-source]").forEach(b=>b.onclick=()=>{const d=data(),same=d.source===b.dataset.source;d.source=same?"":b.dataset.source;d.checks[1]=!same;d.finished=false;write(new Date(),d);render();toast(same?"Activité retirée":"Mouvement validé +1")});app.querySelector(".finish").onclick=summary;app.querySelector(".settings").onclick=settings;app.querySelector(".export").onclick=exportData;app.querySelector("#restore").onchange=e=>e.target.files[0]&&restore(e.target.files[0]);app.querySelector(".info").onclick=about}
render();if("serviceWorker"in navigator)window.addEventListener("load",()=>navigator.serviceWorker.register("./service-worker.js"));
})();

