(()=>{
const app=document.querySelector("#app"),KEY="discovery-up-profile-v2",OLD_KEY="discovery-up-profile-v1",DAY="discovery-up-day-",levels=[["Déclic",0],["Mise en mouvement",70],["Élan",160],["Rythme",270],["Régularité",390],["Engagement",520],["Progression",660],["Endurance",810],["Équilibre",970],["Autonomie",1130],["Vitalité",1280],["Terrain solide",1420]],weekNames=["Lun","Mar","Mer","Jeu","Ven","Sam","Dim"],pillars=[["🌙","Bien récupérer"],["🥗","Bien s’alimenter"],["🌬️","Prendre soin de son terrain"]];
const nanoChallenges=[
{name:"Jumping jacks",family:"Cardio",kind:"jumping",pose:"jumping",text:"Ouvre et referme bras et jambes à ton rythme."},
{name:"Montées de genoux",family:"Cardio",kind:"knees",pose:"knees",text:"Alterne les genoux sans chercher la vitesse."},
{name:"Sautillements légers",family:"Cardio",kind:"hops",pose:"hops",text:"Effectue de petits rebonds souples sur place."},
{name:"Squats contrôlés",family:"Renforcement",kind:"squat",pose:"squat",text:"Plie les jambes puis redresse-toi sans te presser."},
{name:"Chaise contre le mur",family:"Renforcement",kind:"wall",pose:"wall",text:"Tiens la position confortablement, sans forcer."},
{name:"Gainage",family:"Renforcement",kind:"plank",pose:"plank",text:"Garde le corps aligné et respire normalement."},
{name:"Fentes alternées",family:"Renforcement",kind:"lunges",pose:"lunges",text:"Alterne un pas fendu de chaque côté."},
{name:"Burpees sans saut",family:"Renforcement",kind:"burpee",pose:"burpee",text:"Accroupi, planche, puis debout ; le saut reste facultatif."},
{name:"Équilibre sur un pied",family:"Équilibre",kind:"balance",pose:"balance",text:"Change de pied à mi-parcours, près d’un appui."},
{name:"Montées d’escaliers",family:"Vie quotidienne",kind:"stairs",pose:"stairs",text:"Monte quelques marches à ton rythme."},
{name:"Marche active",family:"Mobilité",kind:"walk",pose:"walk",text:"Marche d’un pas confortable et dynamique."},
{name:"Porter une charge adaptée",family:"Vie quotidienne",kind:"carry",pose:"carry",text:"Marche avec une charge légère qui te convient."},
{name:"Pompes contrôlées",family:"Renforcement",kind:"pushup",pose:"pushup",text:"Réalise des pompes propres à ton rythme."},
{name:"Rowing au sac à dos",family:"Renforcement",kind:"rowing",pose:"rowing",text:"Dos stable, tire doucement un sac léger vers toi."},
{name:"Crunchs doux",family:"Renforcement",kind:"crunch",pose:"crunch",text:"Décolle légèrement les épaules sans tirer la nuque."},
{name:"Duo squats + pompes",family:"Duo renforcement",kind:"duo",steps:[{name:"Squats",pose:"squat"},{name:"Pompes",pose:"pushup"}],text:"Un temps de squats, puis le même temps de pompes."},
{name:"Duo genoux + chaise",family:"Duo cardio",kind:"duo",steps:[{name:"Montées de genoux",pose:"knees"},{name:"Chaise",pose:"wall"}],text:"Montées de genoux, puis chaise contre le mur."},
{name:"Duo marche + équilibre",family:"Duo équilibre",kind:"duo",steps:[{name:"Marche sur place",pose:"walk"},{name:"Équilibre",pose:"balance"}],text:"Marche sur place, puis équilibre près d’un appui."},
{name:"Duo fentes + gainage",family:"Duo renforcement",kind:"duo",steps:[{name:"Fentes",pose:"lunges"},{name:"Gainage",pose:"plank"}],text:"Fentes contrôlées, puis gainage."},
{name:"Duo sautillements + squats",family:"Duo cardio",kind:"duo",steps:[{name:"Sautillements",pose:"hops"},{name:"Squats",pose:"squat"}],text:"Petits rebonds, puis squats contrôlés."},
{name:"Duo rowing + équilibre",family:"Duo coordination",kind:"duo",steps:[{name:"Rowing léger",pose:"rowing"},{name:"Équilibre",pose:"balance"}],text:"Rowing avec un sac léger, puis équilibre."},
{name:"Duo jumping jacks + crunchs",family:"Duo cardio",kind:"duo",steps:[{name:"Jumping jacks",pose:"jumping"},{name:"Crunchs",pose:"crunch"}],text:"Jumping jacks, puis crunchs doux."},
{name:"Duo pompes + chaise",family:"Duo renforcement",kind:"duo",steps:[{name:"Pompes",pose:"pushup"},{name:"Chaise",pose:"wall"}],text:"Pompes contrôlées, puis chaise contre le mur."},
{name:"Duo genoux + fentes",family:"Duo coordination",kind:"duo",steps:[{name:"Montées de genoux",pose:"knees"},{name:"Fentes",pose:"lunges"}],text:"Montées de genoux, puis fentes alternées."},
{name:"Duo squats + gainage",family:"Duo renforcement",kind:"duo",steps:[{name:"Squats",pose:"squat"},{name:"Gainage",pose:"plank"}],text:"Squats contrôlés, puis gainage."},
{name:"Pas dynamiques sur place",family:"Mobilité",kind:"walk",pose:"walk",text:"Marche activement sur place en balançant les bras."},
{name:"Escaliers en douceur",family:"Mobilité",kind:"stairs",pose:"stairs",text:"Monte et descends quelques marches sans te presser."},
{name:"Mobilité debout",family:"Mobilité",kind:"balance",pose:"balance",text:"Alterne appui et montée de genou en restant stable."},
{name:"Transport actif",family:"Vie quotidienne",kind:"carry",pose:"carry",text:"Déplace une charge légère avec une posture stable."},
{name:"Duo marche + équilibre",family:"Mobilité",kind:"duo",steps:[{name:"Marche sur place",pose:"walk"},{name:"Équilibre",pose:"balance"}],text:"Marche sur place, puis termine par un équilibre."}
];
let nanoInterval=null,nanoSeconds=45,nanoRemaining=45,nanoRunning=false,nanoFinished=false,nanoPhase=0,nanoTarget=0;
let profile=load(KEY,null)||load(OLD_KEY,{ready:false,program:"walk",custom:"Hydratation",created:new Date().toISOString()});profile=Object.assign({ready:false,program:"walk",custom:"Hydratation",xp:0,bestStreak:0,bagCycleDays:[],bagReady:false,drinkAvailable:false,protectedDays:[],earnedBags:0},profile);
function load(key,fallback){try{return JSON.parse(localStorage.getItem(key))||fallback}catch{return fallback}}
function save(){localStorage.setItem(KEY,JSON.stringify(profile))}
function dateKey(date=new Date()){const y=date.getFullYear(),m=String(date.getMonth()+1).padStart(2,"0"),d=String(date.getDate()).padStart(2,"0");return `${y}-${m}-${d}`}
function normalize(raw={}){if(Array.isArray(raw.movements)&&Array.isArray(raw.pillars)){const oldPillars=raw.pillars.length>=4;return Object.assign({finished:false,earned:{}},raw,{pillars:oldPillars?raw.pillars.slice(1,4):raw.pillars.slice(0,3),schema:3})}const checks=Array.isArray(raw.checks)?raw.checks:[false,false,false,false,false];return {movements:checks[1]?["nano"]:[],pillars:[!!checks[3],!!checks[2],!!checks[0]||!!checks[4]],finished:!!raw.finished,earned:{},legacy:true,schema:3}}
function data(date=new Date()){return normalize(load(DAY+dateKey(date),{}))}function write(day,value){localStorage.setItem(DAY+dateKey(day),JSON.stringify(value));save()}function movementDone(d=data()){return d.movements.length>0}function points(d=data()){return(movementDone(d)?2:0)+d.pillars.filter(Boolean).length}
function allDays(){const out=[];for(let i=0;i<localStorage.length;i++){const k=localStorage.key(i);if(k?.startsWith(DAY)){const raw=load(k,null);if(raw)out.push({key:k.slice(DAY.length),...normalize(raw)})}}return out.sort((a,b)=>a.key.localeCompare(b.key))}
function storedPointsTotal(){let total=0;for(let i=0;i<localStorage.length;i++){const key=localStorage.key(i);if(!key?.startsWith(DAY))continue;const raw=load(key,null);if(Array.isArray(raw?.checks))total+=raw.checks.filter(Boolean).length;else if(raw)total+=points(normalize(raw))}return total}
function previousDay(date){const d=new Date(date);d.setDate(d.getDate()-1);d.setHours(0,0,0,0);return d}function isProtected(key){return(profile.protectedDays||[]).includes(key)}function isActiveKey(key){const row=allDays().find(d=>d.key===key);return!!row&&movementDone(row)}
function applyDrinkProtection(){if(!profile.drinkAvailable)return;const yesterday=previousDay(new Date()),before=previousDay(yesterday),yk=dateKey(yesterday),bk=dateKey(before);if(!isActiveKey(yk)&&!isProtected(yk)&&(isActiveKey(bk)||isProtected(bk))){profile.protectedDays=[...new Set([...(profile.protectedDays||[]),yk])];profile.drinkAvailable=false;profile.drinkNotice=yk;save()}}
function streak(){let cursor=new Date();cursor.setHours(0,0,0,0);if(!isActiveKey(dateKey(cursor))&&!isProtected(dateKey(cursor)))cursor=previousDay(cursor);let n=0;while(isActiveKey(dateKey(cursor))||isProtected(dateKey(cursor))){n++;cursor=previousDay(cursor)}return n}
function monday(date=new Date()){const d=new Date(date);d.setHours(0,0,0,0);d.setDate(d.getDate()-((d.getDay()+6)%7));return d}function weekDates(){const m=monday();return Array.from({length:7},(_,i)=>{const d=new Date(m);d.setDate(m.getDate()+i);return d})}function weeklyPillar(i){return weekDates().reduce((n,d)=>n+(data(d).pillars[i]?1:0),0)}
function levelInfo(){const t=Number(profile.xp)||0;let i=0;levels.forEach((l,n)=>{if(t>=l[1])i=n});return{index:i,number:i+1,name:levels[i][0],next:levels[i+1]||null,total:t}}function pulse(level){return`./assets/pulse/level-${String(level).padStart(2,"0")}.webp`}function toast(msg){document.body.insertAdjacentHTML("beforeend",`<div class="toast">${msg}</div>`);setTimeout(()=>document.querySelector(".toast")?.remove(),2200)}
function pointLabel(n){return`${n} point${n>1?"s":""}`}function motionDayLabel(n){return`${n} jour${n>1?"s":""} en mouvement`}function activeDayLabel(n){return`${n} journée${n>1?"s":""} active${n>1?"s":""}`}function remainingDayLabel(n){return n===1?"Plus qu’une journée active.":`Plus que ${n} journées actives.`}
function movementChoices(){return[["group","Séance avec mon groupe"],["endurance",profile.program==="walk"?"Marche autonome":"Running autonome"],["strength","Renforcement"],["nano","Nano-séance"]]}function earn(d,id){d.earned=d.earned||{};if(!d.earned[id]){d.earned[id]=true;profile.xp=(Number(profile.xp)||0)+1}}function earnMovement(d){d.earned=d.earned||{};if(!d.earned["movement-day"]){d.earned["movement-day"]=true;profile.xp=(Number(profile.xp)||0)+2}}
function nanoChallenge(date=new Date()){const start=new Date(2026,0,1),day=Math.floor((new Date(date.getFullYear(),date.getMonth(),date.getDate())-start)/86400000);return nanoChallenges[((day%nanoChallenges.length)+nanoChallenges.length)%nanoChallenges.length]}
function nanoImage(pose){return`./assets/nano/${pose}.webp`}
function nanoOptions(challenge){if(challenge.kind==="walk"||challenge.kind==="stairs"||challenge.kind==="carry")return[60,120,180];if(["balance","wall","plank"].includes(challenge.kind))return[20,30,45];return[30,45,60]}
function formatNanoTime(seconds){return`${String(Math.floor(seconds/60)).padStart(2,"0")}:${String(seconds%60).padStart(2,"0")}`}
function stopNanoTimer(){if(nanoInterval)clearInterval(nanoInterval);nanoInterval=null;nanoRunning=false}
function resetNanoTimer(seconds=nanoSeconds){stopNanoTimer();nanoSeconds=seconds;nanoRemaining=seconds;nanoFinished=false;nanoPhase=0;updateNanoTimer()}
function updateNanoTimer(){const modal=app.querySelector(".nano-modal");if(!modal)return;modal.querySelector(".nano-time").textContent=formatNanoTime(nanoRemaining);modal.querySelector(".nano-timer").classList.toggle("finished",nanoFinished);const challenge=nanoChallenge(),phase=modal.querySelector(".nano-phase");if(phase&&challenge.steps)phase.textContent=`PHASE ${nanoPhase+1}/2 · ${challenge.steps[nanoPhase].name}`;modal.querySelector(".nano-status").textContent=nanoFinished?"Temps écoulé ! Valide uniquement ce que tu as réellement fait.":nanoRunning?"C’est parti ! Bouge à ton rythme.":"Le chrono est une aide facultative.";modal.querySelector(".nano-start").textContent=nanoRunning?"PAUSE":"LANCER LE CHRONO"}
function startNanoTimer(){if(nanoRunning){nanoRemaining=Math.max(0,Math.ceil((nanoTarget-Date.now())/1000));stopNanoTimer();updateNanoTimer();return}if(nanoRemaining<=0)nanoRemaining=nanoSeconds;nanoRunning=true;nanoFinished=false;nanoTarget=Date.now()+nanoRemaining*1000;updateNanoTimer();nanoInterval=setInterval(()=>{nanoRemaining=Math.max(0,Math.ceil((nanoTarget-Date.now())/1000));if(nanoRemaining===0){const challenge=nanoChallenge();if(challenge.steps&&nanoPhase===0){nanoPhase=1;nanoRemaining=nanoSeconds;nanoTarget=Date.now()+nanoSeconds*1000;const timer=app.querySelector(".nano-timer");timer?.classList.remove("phase-change");void timer?.offsetWidth;timer?.classList.add("phase-change")}else{stopNanoTimer();nanoFinished=true;navigator.vibrate?.([80,60,80])}}updateNanoTimer()},250)}
function toggleMovement(id){profile.drinkNotice="";const d=data(),before=movementDone(d),on=d.movements.includes(id);d.movements=on?d.movements.filter(x=>x!==id):[...d.movements,id];if(!on&&!before)earnMovement(d);d.finished=false;syncBagDay(d,before);write(new Date(),d);render();reward(app.querySelector(`[data-movement="${id}"]`),on?"Mouvement retiré":before?"Activité supplémentaire enregistrée":"Mouvement du jour validé · +2 points",!on&&!before?"+2":"")}
function openNano(){stopNanoTimer();const challenge=nanoChallenge(),selected=data().movements.includes("nano"),options=nanoOptions(challenge);nanoSeconds=options[Math.min(1,options.length-1)];nanoRemaining=nanoSeconds;nanoFinished=false;nanoPhase=0;const illustration=challenge.steps?`<div class="nano-duo">${challenge.steps.map((step,i)=>`<figure><img src="${nanoImage(step.pose)}" alt="${step.name}"><figcaption>${i+1}. ${step.name}</figcaption></figure>`).join("")}</div>`:`<img class="nano-illustration" src="${nanoImage(challenge.pose)}" alt="Illustration : ${challenge.name}">`;app.insertAdjacentHTML("beforeend",`<div class="overlay nano-overlay"><section class="modal nano-modal" role="dialog" aria-modal="true" aria-label="Nano-séance du jour"><button class="nano-close" aria-label="Fermer">×</button><span class="eyebrow">NANO-SÉANCE DU JOUR</span><h2>${challenge.name}</h2><span class="nano-family">${challenge.family}</span>${illustration}<p class="nano-instruction">${challenge.text}</p><div class="nano-timer"><h3>Choisis ton temps${challenge.steps?" pour chaque phase":""}</h3><div class="nano-presets">${options.map(s=>`<button class="${s===nanoSeconds?"on":""}" data-nano-seconds="${s}">${s<60?s+" s":s%60===0?s/60+" min":Math.floor(s/60)+" min "+s%60+" s"}</button>`).join("")}</div>${challenge.steps?`<div class="nano-phase">PHASE 1/2 · ${challenge.steps[0].name}</div>`:""}<div class="nano-time" role="timer">${formatNanoTime(nanoRemaining)}</div><div class="nano-status">Le chrono est une aide facultative.</div><div class="nano-actions"><button class="nano-start">LANCER LE CHRONO</button><button class="nano-reset">RECOMMENCER</button></div></div><button class="primary nano-confirm">${selected?"RETIRER CETTE NANO-SÉANCE":"J’AI RÉALISÉ LA NANO-SÉANCE"}</button><p class="nano-note">Pas de course contre la montre : avance à ton rythme.</p></section></div>`);const modal=app.querySelector(".nano-modal");modal.querySelector(".nano-close").onclick=()=>{stopNanoTimer();app.querySelector(".nano-overlay")?.remove()};modal.querySelectorAll("[data-nano-seconds]").forEach(button=>button.onclick=()=>{modal.querySelectorAll("[data-nano-seconds]").forEach(x=>x.classList.toggle("on",x===button));resetNanoTimer(Number(button.dataset.nanoSeconds))});modal.querySelector(".nano-start").onclick=startNanoTimer;modal.querySelector(".nano-reset").onclick=()=>resetNanoTimer();modal.querySelector(".nano-confirm").onclick=()=>{stopNanoTimer();toggleMovement("nano")}}
function syncBagDay(d,before){const key=dateKey(),now=movementDone(d),set=new Set(profile.bagCycleDays||[]);if(now&&!before)set.add(key);if(!now&&before)set.delete(key);profile.bagCycleDays=[...set].sort();profile.bagReady=profile.bagCycleDays.length>=5}
function migrateBagTracking(){if(profile.bagTrackingSchema===2)return;if((Number(profile.earnedBags)||0)===0){const activeKeys=allDays().filter(movementDone).map(day=>day.key);profile.bagCycleDays=[...new Set(activeKeys)].sort().slice(-5);profile.bagReady=profile.bagCycleDays.length>=5}profile.bagTrackingSchema=2}
function migrateMovementScoring(){if(profile.movementScoringSchema===2)return;let adjustment=0;for(let i=0;i<localStorage.length;i++){const key=localStorage.key(i);if(!key?.startsWith(DAY))continue;const raw=load(key,null);if(!raw)continue;const d=normalize(raw),earned=d.earned=d.earned||{},oldAwards=Object.keys(earned).filter(id=>id.startsWith("move-")).length;if(!earned["movement-day"]&&(oldAwards||movementDone(d))){adjustment+=2-(oldAwards||1);earned["movement-day"]=true;localStorage.setItem(key,JSON.stringify(d))}}profile.xp=Math.max(0,(Number(profile.xp)||0)+adjustment);profile.movementScoringSchema=2}
function bagBlock(){const count=Math.min(5,new Set(profile.bagCycleDays||[]).size);if(profile.bagReady){const full=profile.drinkAvailable;return`<section class="bag-card ready"><img src="./assets/rewards/bag-ready.webp" alt="Sac de sport prêt"><div><span class="eyebrow">5 JOURNÉES ACTIVES SUR 5</span><h3>Ton sac de sport est prêt !</h3><p>${full?"Ta Boisson est encore disponible. Le sac restera fermé jusqu’à son utilisation.":"Ouvre-le pour recevoir ta Boisson du sportif."}</p><button class="open-bag" ${full?"disabled":""}>${full?"INVENTAIRE PLEIN":"OUVRIR MON SAC"}</button></div></section>`}return`<section class="bag-card"><img src="./assets/rewards/bag-closed.webp" alt="Progression vers le sac"><div><span class="eyebrow">PROCHAIN SAC</span><h3>${activeDayLabel(count)} sur 5</h3><div class="bag-meter"><i style="width:${count*20}%"></i></div><p>${remainingDayLabel(5-count)}</p></div></section>`}
function inventory(){return`<div class="inventory ${profile.drinkAvailable?"full":""}"><img src="./assets/rewards/sports-drink.webp" alt="Boisson du sportif"><span><b>Boisson du sportif</b>${profile.drinkAvailable?"Disponible · protège une journée":"Inventaire vide"}</span></div>`}
function render(){if(!profile.ready)return onboarding();applyDrinkProtection();const today=new Date(),d=data(today),lv=levelInfo(),next=lv.next?lv.next[1]:lv.total,prev=levels[lv.index][1],pct=lv.next?Math.round((lv.total-prev)/(next-prev)*100):100,week=weekDates(),series=streak(),history=allDays().some(day=>movementDone(day));profile.bestStreak=Math.max(profile.bestStreak||0,series);save();const movements=movementChoices().map(([id,label])=>`<button class="move-option ${d.movements.includes(id)?"on":""}" data-movement="${id}">${d.movements.includes(id)?"✓ ":""}${label}</button>`).join("");const rows=pillars.map((h,i)=>`<div class="habit" data-habit-row="${i}"><span class="habit-icon">${h[0]}</span><span class="habit-name">${h[1]}</span><button class="check ${d.pillars[i]?"on":""}" data-pillar="${i}" aria-pressed="${d.pillars[i]}">${d.pillars[i]?"✓":""}</button></div>`).join("");const days=week.map((date,i)=>{const x=data(date),key=dateKey(date),done=movementDone(x),protectedDay=isProtected(key);return`<div class="day ${done?"done":""} ${protectedDay?"protected":""} ${key===dateKey(today)?"today":""}">${weekNames[i]}<b>${done?"✓":protectedDay?"🧴":"·"}</b></div>`}).join("");const chart=pillars.map((h,i)=>{const n=weeklyPillar(i);return`<div class="chart-row"><span>${h[0]} ${h[1]}</span><div class="bar"><i style="width:${n/7*100}%"></i></div><b>${n}/7</b></div>`}).join("");const heroTitle=movementDone(d)?`${motionDayLabel(series)} !`:!history?"Ton parcours commence aujourd’hui.":series?"Un mouvement aujourd’hui ?":"Chaque reprise est une victoire.";const remaining=lv.next?lv.next[1]-lv.total:0,drinkUsedToday=profile.drinkNotice===dateKey(previousDay(today));
app.innerHTML=`<div class="shell"><header class="topbar"><img class="brand" src="./logo-discovery-up.svg" alt="Discovery UP"><button class="icon-button settings" aria-label="Réglages">⚙</button></header><div class="season">PROGRAMME 10 MOIS · ${profile.program==="walk"?"MARCHE ACTIVE":"DISCOVERY RUN"}</div><section class="dashboard"><div class="stat"><span>NIVEAU</span><strong>${lv.number}</strong><small>${lv.name}</small></div><div class="stat"><span>SÉRIE</span><strong>${series}</strong><small>${motionDayLabel(series).toUpperCase()}</small></div></section><section class="hero"><img class="pulse" src="${pulse(lv.number)}" alt="Pulse au niveau ${lv.number}"><div class="hero-copy"><h1>${heroTitle}</h1><p>${lv.next?`${pointLabel(remaining)} avant ${lv.next[0]}`:"Niveau maximal atteint"}</p><div class="meter"><span style="width:${Math.max(0,pct)}%"></span></div><div class="meter-label"><span>${pointLabel(lv.total)}</span><span>${pct}%</span></div></div></section>${drinkUsedToday?`<div class="gentle-message">🧴 Ta Boisson du sportif protège ta série aujourd’hui. Reprends ton mouvement demain !</div>`:""}<div class="week">${days}</div><section class="card movement-card"><div class="card-head"><div><span class="eyebrow">SOCLE DE TA SÉRIE</span><h2>Mon mouvement du jour</h2></div><span class="movement-status ${movementDone(d)?"done":""}">${movementDone(d)?"VALIDÉ":"1 CHOIX SUFFIT"}</span></div><div class="movement-grid">${movements}</div><p class="helper">Une seule action maintient ta série. Plusieurs activités restent enregistrées, sans dépasser 2 points.</p></section><section class="card"><div class="card-head"><div><span class="eyebrow">EN COMPLÉMENT</span><h2>Mes piliers de santé</h2></div><span class="date">${pointLabel(points(d))}</span></div>${rows}</section>${bagBlock()}${inventory()}<section class="card"><div class="card-head weekly-head"><div><h2>Mes piliers depuis lundi</h2><p>Semaine en cours · lundi à dimanche</p></div></div>${chart}</section><p class="privacy">🔒 Les données restent uniquement sur cet appareil.</p><div class="signature"><span>par</span><img src="./assets/discovery-sports.webp" alt="Discovery Sports"></div></div>`;bind()}
function onboarding(){app.innerHTML=`<div class="overlay"><section class="modal"><img class="brand" src="./logo-discovery-up.svg" alt="Discovery UP"><img class="pulse" src="./assets/pulse/level-01.webp" alt="Pulse"><h2>Un mouvement chaque jour</h2><p>Construis durablement les piliers de ta santé, en moins de 30 secondes par jour.</p><div class="choice"><button data-program="walk" class="${profile.program==="walk"?"on":""}">🚶<br>Marche Active</button><button data-program="run" class="${profile.program==="run"?"on":""}">🏃<br>Discovery Run</button></div><button class="primary start">COMMENCER</button><div class="signature"><span>par</span><img src="./assets/discovery-sports.webp" alt="Discovery Sports"></div></section></div>`;app.querySelectorAll("[data-program]").forEach(b=>b.onclick=()=>{profile.program=b.dataset.program;onboarding()});app.querySelector(".start").onclick=()=>{profile.ready=true;save();render()}}
function settings(){app.insertAdjacentHTML("beforeend",`<div class="overlay"><section class="modal"><h2>Mes réglages</h2><label>Parcours</label><div class="choice"><button data-program="walk" class="${profile.program==="walk"?"on":""}">🚶<br>Marche Active</button><button data-program="run" class="${profile.program==="run"?"on":""}">🏃<br>Discovery Run</button></div><button class="primary save-settings">ENREGISTRER</button><div class="settings-tools"><button class="secondary export-settings">SAUVEGARDER MES DONNÉES</button><label class="secondary restore-settings" for="restore-settings">RESTAURER MES DONNÉES</label><input id="restore-settings" hidden type="file" accept="application/json"><button class="secondary about-settings">À PROPOS</button></div><button class="secondary close">ANNULER</button><button class="secondary reset">EFFACER MA PROGRESSION</button></section></div>`);const modal=app.querySelector(".overlay");modal.querySelectorAll("[data-program]").forEach(b=>b.onclick=()=>{profile.program=b.dataset.program;modal.querySelectorAll("[data-program]").forEach(x=>x.classList.toggle("on",x===b))});modal.querySelector(".save-settings").onclick=()=>{save();render();toast("Réglages enregistrés")};modal.querySelector(".export-settings").onclick=exportData;modal.querySelector("#restore-settings").onchange=e=>e.target.files[0]&&restore(e.target.files[0]);modal.querySelector(".about-settings").onclick=about;modal.querySelector(".close").onclick=render;modal.querySelector(".reset").onclick=()=>{if(confirm("Effacer toute la progression Discovery UP sur cet appareil ?")){Object.keys(localStorage).filter(k=>k.startsWith("discovery-up-")).forEach(k=>localStorage.removeItem(k));location.reload()}}}
function celebrate(){const pieces=Array.from({length:24},(_,i)=>`<i style="left:${(i*37)%100}%;animation-delay:${(i%6)*.05}s"></i>`).join("");document.body.insertAdjacentHTML("beforeend",`<div class="confetti">${pieces}</div>`);setTimeout(()=>document.querySelector(".confetti")?.remove(),1500)}
function summary(){const d=data(),lv=levelInfo(),score=points(d),series=streak();d.finished=true;write(new Date(),d);app.insertAdjacentHTML("beforeend",`<div class="overlay"><section class="modal" style="text-align:center"><img class="pulse" src="${pulse(lv.number)}" alt="Pulse célèbre"><span class="mission-tag">+${score} ACTION${score>1?"S":""} VALIDÉE${score>1?"S":""}</span><h2>${series===1?"Une nouvelle série commence !":`${series} jours en mouvement !`}</h2><p>Ta progression reste acquise, jour après jour.</p><p>${lv.next?`Encore ${lv.next[1]-lv.total} points avant ${lv.next[0]}.`:"Tu as atteint Terrain solide."}</p><button class="primary close-summary">À DEMAIN</button><button class="secondary edit-summary">MODIFIER MA JOURNÉE</button></section></div>`);celebrate();app.querySelector(".close-summary").onclick=render;app.querySelector(".edit-summary").onclick=render}
function openBag(){if(!profile.bagReady||profile.drinkAvailable)return;profile.drinkAvailable=true;profile.bagReady=false;profile.bagCycleDays=[];profile.earnedBags=(profile.earnedBags||0)+1;save();const sparks=Array.from({length:12},(_,i)=>`<i style="--i:${i}"></i>`).join("");app.insertAdjacentHTML("beforeend",`<div class="overlay reward-overlay"><section class="modal reward-modal"><div class="reward-stage"><span class="reward-halo"></span><span class="reward-sparks" aria-hidden="true">${sparks}</span><img class="reward-bag" src="./assets/rewards/bag-ready.webp" alt="Sac de sport ouvert"><img class="drink-reward" src="./assets/rewards/sports-drink.webp" alt="Boisson du sportif"></div><div class="reward-copy"><span class="mission-tag">RÉCOMPENSE DÉBLOQUÉE</span><h2>Boisson du sportif</h2><p>Elle protégera automatiquement une seule journée oubliée. Elle ne valide pas une activité et ne donne aucun point.</p><button class="primary close-reward">AJOUTER À MON INVENTAIRE</button></div></section></div>`);celebrate();navigator.vibrate?.([60,40,90]);app.querySelector(".close-reward").onclick=render}
function about(){app.insertAdjacentHTML("beforeend",`<div class="overlay"><section class="modal"><img class="brand" src="./logo-discovery-up.svg" alt="Discovery UP"><h2>Un mouvement chaque jour</h2><p>Le mouvement entretient ta série. Tes actions de renforcement, récupération, alimentation et terrain construisent ta progression globale.</p><p>Une interruption ne retire aucun point et ne fait jamais perdre de niveau. Chaque reprise est une victoire.</p><div class="signature"><span>une application de</span><img src="./assets/discovery-sports.webp" alt="Discovery Sports"></div><button class="primary close">FERMER</button></section></div>`);app.querySelector(".close").onclick=render}
function exportData(){const items={};Object.keys(localStorage).filter(k=>k.startsWith("discovery-up-")).forEach(k=>items[k]=localStorage.getItem(k));const a=document.createElement("a"),url=URL.createObjectURL(new Blob([JSON.stringify({format:"discovery-up",version:2,items},null,2)],{type:"application/json"}));a.href=url;a.download="progression-discovery-up.json";a.click();URL.revokeObjectURL(url)}function restore(file){const r=new FileReader();r.onload=()=>{try{const x=JSON.parse(r.result);if(x.format!=="discovery-up"||!x.items)throw 0;Object.entries(x.items).forEach(([k,v])=>{if(k.startsWith("discovery-up-")&&typeof v==="string")localStorage.setItem(k,v)});location.reload()}catch{alert("Ce fichier de sauvegarde n’est pas valide.")}};r.readAsText(file)}
function reward(target,msg,badge="+1"){const character=app.querySelector(".pulse");if(badge)target?.insertAdjacentHTML("beforeend",`<span class="point-float">${badge}</span>`);character?.classList.add("reward");navigator.vibrate?.(24);toast(msg);setTimeout(()=>{target?.querySelector(".point-float")?.remove();character?.classList.remove("reward")},950)}
function bind(){app.querySelectorAll("[data-movement]").forEach(b=>b.onclick=()=>b.dataset.movement==="nano"?openNano():toggleMovement(b.dataset.movement));app.querySelectorAll("[data-pillar]").forEach(b=>b.onclick=()=>{const d=data(),i=+b.dataset.pillar,on=d.pillars[i];d.pillars[i]=!on;if(!on)earn(d,"pillar-"+i);d.finished=false;write(new Date(),d);render();reward(app.querySelector(`[data-habit-row="${i}"]`),on?"Validation retirée":"Ton pilier progresse +1",on?"":"+1")});app.querySelector(".open-bag")?.addEventListener("click",openBag);app.querySelector(".settings").onclick=settings}
migrateMovementScoring();profile.xp=Math.max(Number(profile.xp)||0,storedPointsTotal());migrateBagTracking();save();render();if("serviceWorker"in navigator)window.addEventListener("load",()=>navigator.serviceWorker.register("./service-worker.js"));
})();
